// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oftp4Net.Entity;

#nullable disable

namespace Oftp4Net.Entity.Migrations
{
    [DbContext(typeof(O4NDbContext))]
    [Migration("20260923101815_VirtualFileFormat")]
    partial class VirtualFileFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Havit.Data.EntityFrameworkCore.Model.DataSeedVersion", b =>
                {
                    b.Property<string>("ProfileName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("ProfileName")
                        .HasName("PK_DataSeed");

                    b.ToTable("__DataSeed", (string)null);
                });

            modelBuilder.Entity("Oftp4Net.Domain.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InboxWebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Data")
                        .HasColumnType("text");

                    b.Property<bool>("HasPrivateKey")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SFID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Listener", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateId")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdentityId")
                        .HasColumnType("integer");

                    b.Property<string>("ListenIPAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireClientCertificate")
                        .HasColumnType("boolean");

                    b.Property<int>("Tls")
                        .HasColumnType("integer");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("IdentityId");

                    b.ToTable("Listeners");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AnsiCodePage")
                        .HasColumnType("integer");

                    b.Property<bool>("BufferCompression")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("CompressFiles")
                        .HasColumnType("boolean");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("ConvertIncomingEbcdicToAnsi")
                        .HasColumnType("boolean");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Duns")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EbcdicCodePage")
                        .HasColumnType("integer");

                    b.Property<bool>("EncryptFiles")
                        .HasColumnType("boolean");

                    b.Property<string>("FileCipherSuite")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InboundDsnPatterns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InfoDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OutboundDsnPatterns")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutgoingEncoding")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Password")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("PreviousSecurityCertificateId")
                        .HasColumnType("integer");

                    b.Property<int>("ProtocolLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("RequestSignedEndResponse")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireCompressedFiles")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireEncryptedFiles")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireSignedFiles")
                        .HasColumnType("boolean");

                    b.Property<bool>("Restart")
                        .HasColumnType("boolean");

                    b.Property<string>("SFID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<bool>("SecureAuthentication")
                        .HasColumnType("boolean");

                    b.Property<int?>("SecurityCertificateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SetupAppliedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SetupDocumentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SetupDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SignFiles")
                        .HasColumnType("boolean");

                    b.Property<string>("SubStations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Tls")
                        .HasColumnType("integer");

                    b.Property<int?>("TrustedCertificateId")
                        .HasColumnType("integer");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PreviousSecurityCertificateId");

                    b.HasIndex("SecurityCertificateId");

                    b.HasIndex("TrustedCertificateId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("Oftp4Net.Domain.PartnerSetupDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppliedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Changes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DecidedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DocDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid");

                    b.Property<string>("Messages")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceivedFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("ReceivedFileId");

                    b.HasIndex("Status", "ValidFrom");

                    b.ToTable("PartnerSetupDocuments");
                });

            modelBuilder.Entity("Oftp4Net.Domain.ReceivedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CipherSuite")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("Compressed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DecidedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(999)
                        .HasColumnType("character varying(999)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime?>("FetchedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileDate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaxRecordSize")
                        .HasColumnType("integer");

                    b.Property<string>("NotDeliveredReasonCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Originator")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<long>("Records")
                        .HasColumnType("bigint");

                    b.Property<long>("RestartedFrom")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("SignedResponseRequested")
                        .HasColumnType("boolean");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserData")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("VirtualFileName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("VirtualFileName", "FileDate", "FileTime");

                    b.ToTable("ReceivedFiles");
                });

            modelBuilder.Entity("Oftp4Net.Domain.SendQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CipherSuite")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(999)
                        .HasColumnType("character varying(999)");

                    b.Property<string>("DestinationSfid")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("FileDate")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FileTime")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("IdentityId")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastErrorDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxRecordSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextRetry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("RestartPosition")
                        .HasColumnType("bigint");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SignedResponseRequested")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VirtualFileName")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("VirtualFileName", "FileDate", "FileTime");

                    b.ToTable("SendQueueItems");
                });

            modelBuilder.Entity("Oftp4Net.Domain.SettingsItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("Oftp4Net.Domain.TransferEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FileDate")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileTime")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PartnerId")
                        .HasColumnType("integer");

                    b.Property<string>("PartnerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ReceivedFileId")
                        .HasColumnType("integer");

                    b.Property<string>("RemoteEndPoint")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SendQueueItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("VirtualFileName")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived", "Timestamp");

                    b.HasIndex("Category", "IsArchived", "Timestamp");

                    b.ToTable("TransferEvents");
                });

            modelBuilder.Entity("Oftp4Net.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Listener", b =>
                {
                    b.HasOne("Oftp4Net.Domain.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Oftp4Net.Domain.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Certificate");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Oftp4Net.Domain.Partner", b =>
                {
                    b.HasOne("Oftp4Net.Domain.Certificate", "PreviousSecurityCertificate")
                        .WithMany()
                        .HasForeignKey("PreviousSecurityCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Oftp4Net.Domain.Certificate", "SecurityCertificate")
                        .WithMany()
                        .HasForeignKey("SecurityCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Oftp4Net.Domain.Certificate", "TrustedCertificate")
                        .WithMany()
                        .HasForeignKey("TrustedCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviousSecurityCertificate");

                    b.Navigation("SecurityCertificate");

                    b.Navigation("TrustedCertificate");
                });

            modelBuilder.Entity("Oftp4Net.Domain.PartnerSetupDocument", b =>
                {
                    b.HasOne("Oftp4Net.Domain.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Oftp4Net.Domain.ReceivedFile", "ReceivedFile")
                        .WithMany()
                        .HasForeignKey("ReceivedFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partner");

                    b.Navigation("ReceivedFile");
                });

            modelBuilder.Entity("Oftp4Net.Domain.ReceivedFile", b =>
                {
                    b.HasOne("Oftp4Net.Domain.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Oftp4Net.Domain.SendQueueItem", b =>
                {
                    b.HasOne("Oftp4Net.Domain.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Oftp4Net.Domain.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
